// Code generated by genevent. DO NOT EDIT.

package voicegateway

import "github.com/diamondburned/arikawa/v3/utils/ws"

func init() {
	OpUnmarshalers.Add(
		func() ws.Event { return new(IdentifyCommand) },
		func() ws.Event { return new(SelectProtocolCommand) },
		func() ws.Event { return new(ReadyEvent) },
		func() ws.Event { return new(HeartbeatCommand) },
		func() ws.Event { return new(SessionDescriptionEvent) },
		func() ws.Event { return new(SpeakingEvent) },
		func() ws.Event { return new(HeartbeatAckEvent) },
		func() ws.Event { return new(ResumeCommand) },
		func() ws.Event { return new(HelloEvent) },
		func() ws.Event { return new(ResumedEvent) },
		func() ws.Event { return new(ClientsConnectEvent) },
		func() ws.Event { return new(ClientDisconnectEvent) },
		func() ws.Event { return new(DavePrepareTransitionEvent) },
		func() ws.Event { return new(DaveExecuteTransitionEvent) },
		func() ws.Event { return new(DaveReadyForTransitionCommand) },
		func() ws.Event { return new(DavePrepareEpochEvent) },
		func() ws.Event { return new(MLSExternalSenderPackageEvent) },
		func() ws.Event { return new(MLSKeyPackageCommand) },
		func() ws.Event { return new(MLSProposalsEvent) },
		func() ws.Event { return new(MLSCommitWelcomeCommand) },
		func() ws.Event { return new(MLSPrepareCommitTransitionEvent) },
		func() ws.Event { return new(MLSWelcomeEvent) },
		func() ws.Event { return new(MLSInvalidCommitWelcomeCommand) },
	)
}

// Op implements Event. It always returns Op 0.
func (*IdentifyCommand) Op() ws.OpCode { return 0 }

// EventType implements Event.
func (*IdentifyCommand) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 1.
func (*SelectProtocolCommand) Op() ws.OpCode { return 1 }

// EventType implements Event.
func (*SelectProtocolCommand) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 2.
func (*ReadyEvent) Op() ws.OpCode { return 2 }

// EventType implements Event.
func (*ReadyEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 3.
func (*HeartbeatCommand) Op() ws.OpCode { return 3 }

// EventType implements Event.
func (*HeartbeatCommand) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 4.
func (*SessionDescriptionEvent) Op() ws.OpCode { return 4 }

// EventType implements Event.
func (*SessionDescriptionEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 5.
func (*SpeakingEvent) Op() ws.OpCode { return 5 }

// EventType implements Event.
func (*SpeakingEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 6.
func (*HeartbeatAckEvent) Op() ws.OpCode { return 6 }

// EventType implements Event.
func (*HeartbeatAckEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 7.
func (*ResumeCommand) Op() ws.OpCode { return 7 }

// EventType implements Event.
func (*ResumeCommand) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 8.
func (*HelloEvent) Op() ws.OpCode { return 8 }

// EventType implements Event.
func (*HelloEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 9.
func (*ResumedEvent) Op() ws.OpCode { return 9 }

// EventType implements Event.
func (*ResumedEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 11.
func (*ClientsConnectEvent) Op() ws.OpCode { return 11 }

// EventType implements Event.
func (*ClientsConnectEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 13.
func (*ClientDisconnectEvent) Op() ws.OpCode { return 13 }

// EventType implements Event.
func (*ClientDisconnectEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 21.
func (*DavePrepareTransitionEvent) Op() ws.OpCode { return 21 }

// EventType implements Event.
func (*DavePrepareTransitionEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 22.
func (*DaveExecuteTransitionEvent) Op() ws.OpCode { return 22 }

// EventType implements Event.
func (*DaveExecuteTransitionEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 23.
func (*DaveReadyForTransitionCommand) Op() ws.OpCode { return 23 }

// EventType implements Event.
func (*DaveReadyForTransitionCommand) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 24.
func (*DavePrepareEpochEvent) Op() ws.OpCode { return 24 }

// EventType implements Event.
func (*DavePrepareEpochEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 25.
func (*MLSExternalSenderPackageEvent) Op() ws.OpCode { return 25 }

// EventType implements Event.
func (*MLSExternalSenderPackageEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 26.
func (*MLSKeyPackageCommand) Op() ws.OpCode { return 26 }

// EventType implements Event.
func (*MLSKeyPackageCommand) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 27.
func (*MLSProposalsEvent) Op() ws.OpCode { return 27 }

// EventType implements Event.
func (*MLSProposalsEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 28.
func (*MLSCommitWelcomeCommand) Op() ws.OpCode { return 28 }

// EventType implements Event.
func (*MLSCommitWelcomeCommand) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 29.
func (*MLSPrepareCommitTransitionEvent) Op() ws.OpCode { return 29 }

// EventType implements Event.
func (*MLSPrepareCommitTransitionEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 30.
func (*MLSWelcomeEvent) Op() ws.OpCode { return 30 }

// EventType implements Event.
func (*MLSWelcomeEvent) EventType() ws.EventType { return "" }

// Op implements Event. It always returns Op 31.
func (*MLSInvalidCommitWelcomeCommand) Op() ws.OpCode { return 31 }

// EventType implements Event.
func (*MLSInvalidCommitWelcomeCommand) EventType() ws.EventType { return "" }
